key: ${spring.profiles.active}
jasypt:
  encryptor:
    password: ${key}
    bean: jasyptEncryptor
datasource:
  web:
    driver-class-name: ENC(ahNx+x/DY19+90SGknMpuHZ48Isl7lvAbt4pBcjtVeX5bfBzNfA9gEt43yVXuIg1Hp2UNwdZF/iUOWZ7GU2aJA==)
    url: ENC(0/E1DX69ucDAAgKQJW2zk2d2YMLQXNxh3y80dML86d62KcYZrzfVxt8QSTy7YnZHcLq/VlGWfUzl5dDV0hHkRVzI7riSDSP7rmd70/+jQwQ=)
    username: ENC(pzoKtT2jS7NdVpN7w+VDVxz65E9+i21s6s0PitXdFXBMwFFbK9rr0vAPQ7l+FuBx)
    password: ENC(3Px4qC1DxXY4Zr5YG89uG5XTZsDnG5Jc2YMJhRbQrGA2SZ5Fy4tp2nqVPV6M31t9)
  tunneling:
    database:
      driver-class-name: ENC(3lGlQTQzl2VJ0O1l0UUc8L1kskQvxld5Z+Y9CVKRABZfPLT/PkvqW8ljASqf8I27mNubKyAee1ULbLY6j0aIAA==)
      schema: ENC(Bjmy3/lztuG6WCSwUv9T4dhPHfintbHEROtdA31ZV48cYVjXph+ccqN4O1hJHjyg)
      port: ENC(w8TRQEqFz0G1hql5IfXpi0Z8ArmWXYY1tB6d5CpBAksCPirfmCKZOqQt2+e8nm1r)
      username: ENC(brdbXRK/hVcsfbpNf/VhUiZqjxW45goTIVhY2fVZwInSrwLOprNhqFuP0weDWRK/)
      password: ENC(6CQxUwieWdW5sCNHYzeYuiL42iKBPDGRRxnppNsCsr3jOhtUAn7SHO2eqoB0UoV8)
    ssh:
      host: ENC(rEK+VMRZwSiFCYJSHJE1mfM8oyYI3hL1A+Q8F6o3pKuHq+CbrDozmwvprUW5S0J4v2tFKV6Wejgem/LBxXk/pw==)
      port: ENC(SvA53DXJWrxBC/jrtyPX6hHLSqAkpuUOAPAok28DTpQ0Il0ZU6mZ0jSEGo3vlzDS)
      username: ENC(fHKAO6a5Xa0jzTXp6w8k4I3dwESUEz47u+paUEaCjZejdaJhO41KXGkzYrXVl2hj)
      password: ENC(azmQwYxU5UAotIMfrjQ8KxzLSJOuzfrXBGG5S3L4Y2d+SvEFUqZIIUHZOL/3Pf5E)
logup:
  level: INFO # ALL, INFO, WARN, ERROR, OFF
  log-format:
    placeholder: "{datetime} {level}  - {msg}{new-line}"
    date-time-format: yyyy-MM-dd HH:mm:ss
server:
  port: 80