jasypt:
  encryptor:
    password: ${spring.profiles.active}
salt: ${spring.profiles.active}
spring:
  application:
    name: corknote
  test:
    username: ENC(ZQyMWTy27sp22By27RcthA==)
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
